"use client"

import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { RecoilRoot } from "recoil";
import Nav_ from "./components/Nav_";
import Auth_ from "./components/Auth_";
import { Tag_ } from "./page";
import Overlay_ from "./components/Overlay_";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "InSho! - Insurance Training",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* @ts-ignore */}
      <title>{metadata?.title}</title>
      <body className={inter.className}>
        <RecoilRoot>
          {children}
          {/* <div className={``}>

          </div> */}
          <Tag_ initials="Sho!" />
          </RecoilRoot>
      </body>
    </html>
  );
}
